"""
Django settings for reconciliation_api project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import environ
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
PROJECT_DIR = os.path.abspath(os.path.dirname(__file__))
PROJECT_BASE = os.path.abspath(os.path.join(PROJECT_DIR, ".."))

env = environ.Env(DEBUG=(bool, True))
env_file = os.path.join(PROJECT_BASE, ".env")

 # Use a local secret file, if provided. Extendable to pull secrets from cloud or other systems
if os.path.isfile(env_file):
    env.read_env(env_file)
else:
    raise Exception("No local .env detected. No secrets found.")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = env("RECONCILIATION_SECRET_KEY")
DEBUG = bool(env("RECONCILIATION_DEBUG"))


ALLOWED_HOSTS = env("RECONCILIATION_ALLOWED_HOSTS").split(",")
CSRF_TRUSTED_ORIGINS = env("RECONCILIATION_TRUSTED_ORIGINS").split(",")
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'data_reconciliation_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'data_reconciliation_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": env("RECONCILIATION_DATABASE_ENGINE", default="django.db.backends.postgresql"),
        "NAME": env("RECONCILIATION_DATABASE_NAME", default="data_reconciliation"),
        "USER": env("RECONCILIATION_DATABASE_USER", default="postgres"),
        "PASSWORD": env("RECONCILIATION_DATABASE_PASSWORD", default="password"),
        "HOST": env("RECONCILIATION_DATABASE_HOST", default="127.0.0.1"),
        "PORT": env("RECONCILIATION_DATABASE_PORT", default="5432"),
    }
}

APPEND_SLASH=True

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Firebase Settings
FIREBASE_ADMIN_CREDENTIALS = env(
    "FIREBASE_ADMIN_CREDENTIALS", 
    default=os.path.join(PROJECT_BASE, "firebase-service-account.json")
)

# Django Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Data Reconciliation API",
    "DESCRIPTION": "API documentation for Data Reconciliation API project.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}
