# Generated by Django 5.2.4 on 2025-08-19 01:01

import csv_handler.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVDataReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file', models.FileField(upload_to=csv_handler.models.upload_directory_path)),
                ('target_file', models.FileField(upload_to=csv_handler.models.upload_directory_path)),
                ('unique_fields', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=10)),
                ('report', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
